### PR TITLE
fix: adds weighted average feature

### LINKED ISSUE #1: Weighted averages
Currently, the explorer only averages the sample and _not_ geographically weighted averages (the weights for which are available in the original data by Vonter). This should be fixed.

We can consider adding an option to calculate normal average vs weighted too.

### PR DESCRIPTION
**Pull request by thedivtagguy**
Two fixes: 

1. Added nsc_person and mult_person weight columns to data extraction. Added UI toggle for weighted/unweighted calculations. 
2. Improved midnight-crossing activity handling by adding 24 hours (1440 minutes) when end time is earlier than start time

Closes #1

### CODE REVIEW

File: src/lib/duckdb/queryExecutor.ts [hunk 1]
```diff
@@ -403,40 +405,91 @@ async function calculateTimeSpentByDemographic(
...
-    ${whereClause}
-    ${groupByClause}
-    ORDER BY ${groupByColumns.join(', ')}
-  `;
-  
-  console.log(`Executing time spent query on full dataset: ${query}`);
+
+  let query;
+
+  if (useWeightedAverage) {
```
Comment (thedivtagguy) [inline src/lib/duckdb/queryExecutor.ts:418]: This is the new calculation

File: src/lib/duckdb/queryExecutor.ts [hunk 2]
```diff
@@ -403,40 +405,91 @@ async function calculateTimeSpentByDemographic(
...
+/**
+ * Register time calculation function in DuckDB
+ * This should be called during DB initialization
+ */
+async function registerTimeFunctions(db: any): Promise<void> {
+  const conn = await db.connect();
+  try {
+    // Create a SQL function for time difference calculation
+    await conn.query(`
+      CREATE OR REPLACE FUNCTION time_diff_minutes(time_from, time_to) AS
```
Comment (thedivtagguy) [inline src/lib/duckdb/queryExecutor.ts:460]: This fixes the midnight calculation which was resulting in negative numbers
